### ISSUE TITLE
The deploy action should preserve wp-content/index.php

### ISSUE THREAD

**Issue by kirtangajjar** [rtCamp/action-deploy-wordpress#1]
Currently, the deploy action is removing the entire wp-content directory and adding files from the repo. However, it's also removing `wp-content/index.php` file which is part of WordPress core. 

Due to this, Integrity check plugins like Sucuri think that WordPress core is modified and start throwing a warning.

![Screenshot 2019-03-13 at 6 22 51 PM](https://user-images.githubusercontent.com/8456197/54280342-3f05f000-45bd-11e9-9880-11ba9450be0a.png)

Before removing wp-content, we should copy the `wp-content/index.php` to a temporary directory and copy it back after adding files from repo.

**Comment by rahul286** [comment]
Can we have `wp-content/index.php` in our skeleton repo?
