### ISSUE TITLE
WP_VERSION: 6.0 in push.yml gets the value 6 in the script

### ISSUE THREAD

**Issue by dhsathiya** [rtCamp/action-deploy-wordpress#33]
`WP_VERSION : 6.0` in `push.yml`
```
Downloading WordPress 6 (en_US)...
Error: Release not found. Double-check locale or version.
rm: cannot remove 'wp-content/': No such file or directory
➤ Executing task deploy:prepare
✔ Ok
➤ Executing task deploy:unlock
✔ Ok
➤ Executing task deploy:lock
✔ Ok
```

When auto minor updates were on:
```
6 is the latest minor version.
Downloading WordPress 6 (en_US)...
Error: Release not found. Double-check locale or version.
rm: cannot remove 'wp-content/': No such file or directory
```

As an immediate fix, switching the `WP_VERSION` to `latest` worked

**Comment by mrrobot47** [comment]
If it is not in double-quotes, the last `.0` is ignored by GitHub actions.

**Comment by dhsathiya** [comment]
Rel: https://github.com/actions/runner/issues/849
cc: @mrrobot47

**Comment by mrrobot47** [comment]
Agree with the answer, quoting is the only solution.

**Comment by mrrobot47** [comment]
Agree with the answer, quoting is the only solution.
Have already updated with readme [with note to use quotes.](https://github.com/rtCamp/action-deploy-wordpress/commit/cae7310c27daa0380dd0e1b71f01f39ffda58bb2)
