### ISSUE TITLE
On branch deletion GH action deploys on production

### ISSUE THREAD

**Issue by abhijitrakas** [rtCamp/action-deploy-wordpress#7]
I have created a branch(from the master which is used in production env), did some changes and merged that branch into `develop` branch(this is dev env). After I merged, I deleted the branch.

There is no direct connection of the branch deletion with production env. But, after I delete that branch GH action deploys on production with `null` in the message.

**Comment by mbtamuli** [comment]
@abhijitrakas  Can you provide the links to the branch, commit and/or the action relevant to this issue?

**Comment by abhijitrakas** [comment]
@mbtamuli Here is the PR https://github.com/rtCamp/rtcamp-wordpress-mu/pull/161 which I merged and later deleted the branch.

**Comment by chandrapatel** [comment]
@mbtamuli @mrrobot47 Can you please take this issue in priority? Because this issue block us from cleanup the branches. Thanks.

**Comment by mrrobot47** [comment]
On branch deletion, `on_push` GH event is triggered to the branch in which the PR has been merged. That's why when deleting the branches that have been merged to `master` are causing the deployment to prod env.

**Comment by mrrobot47** [comment]
This can be fixed by adding an extra check of branch deletion in `event.json` available in GH action run.
Checking and fixing it.

**Comment by chandrapatel** [comment]
@mrrobot47 What if we close the PR without merging it?

**Comment by mrrobot47** [comment]
Then it should not cause any issues. Even for the other case, I am fixing it and will create a PR in some time.

**Comment by mrrobot47** [comment]
Tested the scenarios in a new repo:

1. Branch deleted of merged PR -> triggered `on="push"` GH action workflow run for `master` branch. (Regardless of where it was merged).
2. Branch deleted of un-merged PR -> triggered `on="push"` GH action workflow run for `master` branch.

**Comment by mrrobot47** [comment]
Fixed in  https://github.com/rtCamp/action-deploy-wordpress/commit/2bf26ca64d7cf36c6db15c4cde3cc9f010b3064f
