### ISSUE TITLE
Deploy stops if you delete the branch immediately

### ISSUE THREAD

**Issue by divyarajmasani** [rtCamp/action-deploy-wordpress#9]
tldr;
If you delete the branch before the deploy action is completed, the action will exit without deploying the latest changes.

This conditional doesn't check which branch is deleted, so if a dev merges a PR and deletes the branch it stops the deployment as well.
Ideally once a PR is merged deployment should not bother with any branch other then the one which is used for deployment,

>https://github.com/rtCamp/action-deploy-wordpress/blob/master/main.sh#L27

check here the last line in the following log of recent gitHub action on OZY
>https://github.com/rtCamp/ozy.com/runs/156164779

**Comment by mrrobot47** [comment]
This has been fixed. Closing it.
